name: synthrouting
channels:
  - anaconda
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - pip
  - cudatoolkit
  - cudnn
  - cuda-nvcc
  - pip:
      - jax[cuda12]  # Replace cuda12 with your CUDA version
      - -e .[dev]
